# references: https://hub.docker.com/r/bitnami/mysql

version: "2"

services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/bitnami/mysql/data"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=random_password
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_general_ci
      - MYSQL_DATABASE=mydb
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mysql/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
  redis:
    image: docker.io/bitnami/redis:6.2.14
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=random_password
      # - REDIS_IO_THREADS = 4
      # - REDIS_AOF_ENABLED = no
      # - REDIS_ACLFILE=/opt/bitnami/redis/mounted-etc/users.acl
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"
  minio:
    image: docker.io/bitnami/minio:2023
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=random_password
      - MINIO_DEFAULT_BUCKETS=mybucket
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio_data:/bitnami/minio/data"

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
