# golangci-lint configuration for v2.5.0+
# See: https://golangci-lint.run/docs/configuration/

version: "2"

run:
  timeout: 10m
  modules-download-mode: readonly
  concurrency: 4

severity:
  default: error

linters:
  # v2 config does not support `disable-all`; use `default: none` instead
  default: none
  enable:
    # Essential linters for code quality
    - errcheck
    - govet
    - ineffassign
    - staticcheck

    # Security and bug detection
    - gosec
    - bodyclose
    - rowserrcheck
    - sqlclosecheck

    # Code style (less strict)
    - misspell
    - unconvert

    # Performance
    - prealloc

    # Import management
    - depguard

    # Documentation
    - godoclint

    # Additional useful linters (less noisy)
    - asciicheck
    - durationcheck
    - errname
    - errorlint
    - nilerr
    - predeclared
    - wastedassign

  # Linter-specific settings (moved under linters.settings for v2)
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: "github.com/pkg/errors"
              desc: "Use github.com/cockroachdb/errors instead"

    errcheck:
      check-type-assertions: true
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)

    godoclint:
      # Default set of rules to enable.
      # Possible values are: `basic`, `all` or `none`.
      # Default: `basic` (enables `pkg-doc`, `single-pkg-doc`, `start-with-name`, and `deprecated`)
      default: basic
      # List of rules to enable in addition to the default set.
      enable:
        # Check proper package-level godoc, if any.
        - pkg-doc
        # Assert at most one godoc per package.
        - single-pkg-doc
        # Check godocs start with the corresponding symbol name.
        - start-with-name
        # Check deprecated symbols have proper deprecation notice.
        - deprecated

    lll:
      line-length: 120

    misspell:
      locale: US

    prealloc:
      simple: true
      range-loops: true
      for-loops: false

    staticcheck:
      checks: ["all", "-QF1008", "-ST1001"]

  # Exclusions moved under linters.exclusions for v2
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    rules:
      # Exclude lll issues for long lines with go:generate
      - linters:
          - lll
        source: "^//go:generate "
      # Relax complexity in tests
      - path: _test\.go
        linters:
          - gosec
          - godoclint
      # Ignore nilerr in specific patterns (example)
      # - linters:
      #     - nilerr
      #   text: "error is not nil but it returns nil"

issues:
  # Increase max issues to avoid truncation
  max-same-issues: 100
