// Code generated by golib; DO NOT EDIT.
package service

import (
	"demo/service/config/namespace/app"
	"demo/service/config/namespace/app/env/item"

	"github.com/forbearing/golib/service"
	"github.com/forbearing/golib/types/consts"
)

func init() {
	service.Register[*item.Lister](consts.PHASE_LIST)
	service.Register[*app.Lister](consts.PHASE_LIST)
}
