// Code generated by gst; DO NOT EDIT.
package service

import (
	"demo/service/config/namespace/app"
	"demo/service/config/namespace/app/env/file"
	"demo/service/config/namespace/app/env/item"
	"demo/service/config/namespace/app/env/itemparse"

	"github.com/forbearing/gst/service"
	"github.com/forbearing/gst/types/consts"
)

func init() {
	service.Register[*file.Lister](consts.PHASE_LIST)
	service.Register[*item.Lister](consts.PHASE_LIST)
	service.Register[*itemparse.Creator](consts.PHASE_CREATE)
	service.Register[*app.Lister](consts.PHASE_LIST)
}
