// Code generated by golib; DO NOT EDIT.
package main

import (
	_ "demo/configx"
	_ "demo/cronjob"
	_ "demo/middleware"
	_ "demo/model"
	"demo/router"
	_ "demo/service"

	"github.com/forbearing/golib/bootstrap"
	. "github.com/forbearing/golib/util"
)

func main() {
	RunOrDie(bootstrap.Bootstrap)
	RunOrDie(router.Init)
	RunOrDie(bootstrap.Run)
}
