// Code generated by golib; DO NOT EDIT.
package model

import (
	"demo/model/iam"
	"demo/model/setting"

	"github.com/forbearing/golib/model"
)

func init() {
	model.Register[*iam.Group]()
	model.Register[*iam.User]()
	model.Register[*setting.Project]()
	model.Register[*setting.Region]()
	model.Register[*setting.Tenant]()
	model.Register[*setting.Vendor]()
}
